version: '3.8'

services:
  sqlserver:
    container_name: sqlserver
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: always
    ports:
      - 1433:1433
    environment:
  # USUARIO PARA CONECTAR ES: SA
      SA_PASSWORD: Apuntes@Net!
      ACCEPT_EULA: Y
    volumes:
      - sqlserver_data:/var/opt/mssql
volumes:
  sqlserver_data: