services:
  garnet:
    container_name: garnet
    image: ghcr.io/microsoft/garnet
    restart: always
    ulimits:
      memlock: -1
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
#    command: --auth Password --password 123456
    volumes:
      - garnetdata:/data

volumes:
  garnetdata: