version: '3.8'

services:
  mariadb:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example
    volumes:
      - ./initDatabase.sql:/docker-entrypoint-initdb.d/init.sql
      - mariabdb_data:/var/lib/mysql
volumes:
  mariabdb_data:
