version: '3.8'

services:
  sqlserver:
    container_name: sqlserver
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: always
    ports:
      - 1433:1433
    environment:
  # USUARIO PARA CONECTAR ES: SA
      SA_PASSWORD: Apuntes@Net!
      ACCEPT_EULA: Y

  postgresql:
    container_name: postgresql
    image: "postgres:latest"
    restart: always
    ports: 
      - 5432:5432
    environment: 
      POSTGRES_PASSWORD: 123456

  redis:
    container_name: redis
    image: 'bitnami/redis:latest'
    ports:
      - 6379:6379
    environment:
      - REDIS_PASSWORD=password123