version: '3.8'

services:

  mysql:
    container_name: mysql
    image: mysql:latest
    restart: always
    ports: 
      - 3307:3307
    environment: 
      MYSQL_ROOT_PASSWORD: '123456'
    # command: --init-file /data/application/initMysql.sql
    # volumes: 
      #- .docker/bbdd/initMysql.sql:/data/application/initMysql.sql

  mariadb:
    container_name: mariadb
    image: mariadb:latest
    restart: always
    ports: 
      - 3306:3306
    environment: 
      MARIADB_ROOT_PASSWORD: '123456'
    # command: --init-file /data/application/initMariadb.sql
    # volumes: 
      #- .docker/bbdd/initMariadb.sql:/data/application/initMariadb.sql

  mongodb:
    container_name: mongodb
    image: mongo
    restart: always
    ports:
      - 27017-27019:27017-27019
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    # volumes:
      #- .docker/bbdd/initMongoDB.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
  
  # USUARIO PARA CONECTAR ES: SA
  sqlserver:
    container_name: sqlserver
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: always
    ports:
      - 1433:1433
    environment:
      SA_PASSWORD: Apuntes@Net!
      ACCEPT_EULA: Y

  postgresql:
    container_name: postgresql
    image: "postgres:latest"
    restart: always
    ports: 
      - 5432:5432
    environment: 
      POSTGRES_PASSWORD: 123456

  redis:
    container_name: redis
    image: 'bitnami/redis:latest'
    ports:
      - 6379:6379
    environment:
      - REDIS_PASSWORD=password123