version: '3.9'

services:
  vault:
    image: vault:latest
    container_name: vault
    ports:
      - 8200:8200
    environment:
      VAULT_ADDR: "http://127.0.0.1:8200"
      # in production scenarios the token mechanisim for loggin will be forbidden,
      # it cannot be in source control.
      VAULT_TOKEN: "token-validacion" # to be able to use the cli on dev
      VAULT_DEV_ROOT_TOKEN_ID: "token-validacion"
    cap_add:
      - IPC_LOCK
