version: '3.8'

services:
  grafana:
  image: grafana/grafana:latest
  container_name: grafana
  environment:
    - GF_SECURITY_ADMIN_USER=admin
    - GF_SECURITY_ADMIN_PASSWORD=admin
    - GF_USERS_ALLOW_SIGN_UP=false
  volumes:
    - ./docker/Observability/Grafana.yaml:/etc/grafana/provisioning/datasources/Grafana.yaml
  ports:
    - 3000:3000