services:
  ## API ##
  app:
    image: /:latest
    restart: always
    environment:
      - ENVIRONMENT__VARIABLE
    ports:
      - "80:80"
      - "443:443"
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost/health | grep -w 'healthy' || exit 1"]
      interval: 1s
      timeout: 10s
      retries: 3
      start_period: 2s
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1.0"
          memory: 512M
        reservations:
          cpus: "0.5"
          memory: 256M
      restart_policy:
        condition: on-failure
    volumes:
      - app_keys_data:/keysFolder

volumes:
  app_keys_data:
